// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/6/20 21:08:33
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/lhd067/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/components/common/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/components/canvas/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/components/materials/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/components/filters/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/components/labels/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/components/export/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/plugins/**/*.{js,ts,mjs}","D:/lhd067/composables/**/*.{js,ts,mjs}","D:/lhd067/utils/**/*.{js,ts,mjs}","D:/lhd067/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/lhd067/app.config.{js,ts,mjs}","D:/lhd067/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;