
interface _GlobalComponents {
      'AnimatedButton': typeof import("../components/common/AnimatedButton.vue")['default']
    'WatercolorBg': typeof import("../components/common/WatercolorBg.vue")['default']
    'CanvasToolbar': typeof import("../components/canvas/CanvasToolbar.vue")['default']
    'FabricCanvas': typeof import("../components/canvas/FabricCanvas.vue")['default']
    'LayerPanel': typeof import("../components/canvas/LayerPanel.vue")['default']
    'TextPropertyPanel': typeof import("../components/canvas/TextPropertyPanel.vue")['default']
    'MaterialCard': typeof import("../components/materials/MaterialCard.vue")['default']
    'MaterialCategory': typeof import("../components/materials/MaterialCategory.vue")['default']
    'MaterialPanel': typeof import("../components/materials/MaterialPanel.vue")['default']
    'UserMaterialPanel': typeof import("../components/materials/UserMaterialPanel.vue")['default']
    'FilterPanel': typeof import("../components/filters/FilterPanel.vue")['default']
    'FilterPreview': typeof import("../components/filters/FilterPreview.vue")['default']
    'LabelEditor': typeof import("../components/labels/LabelEditor.vue")['default']
    'LabelPreview': typeof import("../components/labels/LabelPreview.vue")['default']
    'A4Preview': typeof import("../components/export/A4Preview.vue")['default']
    'ExportPanel': typeof import("../components/export/ExportPanel.vue")['default']
    'BackgroundRemovalPanel': typeof import("../components/BackgroundRemovalPanel.vue")['default']
    'ColorAdjustmentPanel': typeof import("../components/color/ColorAdjustmentPanel.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAnimatedButton': typeof import("../components/common/AnimatedButton.vue")['default']
    'LazyWatercolorBg': typeof import("../components/common/WatercolorBg.vue")['default']
    'LazyCanvasToolbar': typeof import("../components/canvas/CanvasToolbar.vue")['default']
    'LazyFabricCanvas': typeof import("../components/canvas/FabricCanvas.vue")['default']
    'LazyLayerPanel': typeof import("../components/canvas/LayerPanel.vue")['default']
    'LazyTextPropertyPanel': typeof import("../components/canvas/TextPropertyPanel.vue")['default']
    'LazyMaterialCard': typeof import("../components/materials/MaterialCard.vue")['default']
    'LazyMaterialCategory': typeof import("../components/materials/MaterialCategory.vue")['default']
    'LazyMaterialPanel': typeof import("../components/materials/MaterialPanel.vue")['default']
    'LazyUserMaterialPanel': typeof import("../components/materials/UserMaterialPanel.vue")['default']
    'LazyFilterPanel': typeof import("../components/filters/FilterPanel.vue")['default']
    'LazyFilterPreview': typeof import("../components/filters/FilterPreview.vue")['default']
    'LazyLabelEditor': typeof import("../components/labels/LabelEditor.vue")['default']
    'LazyLabelPreview': typeof import("../components/labels/LabelPreview.vue")['default']
    'LazyA4Preview': typeof import("../components/export/A4Preview.vue")['default']
    'LazyExportPanel': typeof import("../components/export/ExportPanel.vue")['default']
    'LazyBackgroundRemovalPanel': typeof import("../components/BackgroundRemovalPanel.vue")['default']
    'LazyColorAdjustmentPanel': typeof import("../components/color/ColorAdjustmentPanel.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AnimatedButton: typeof import("../components/common/AnimatedButton.vue")['default']
export const WatercolorBg: typeof import("../components/common/WatercolorBg.vue")['default']
export const CanvasToolbar: typeof import("../components/canvas/CanvasToolbar.vue")['default']
export const FabricCanvas: typeof import("../components/canvas/FabricCanvas.vue")['default']
export const LayerPanel: typeof import("../components/canvas/LayerPanel.vue")['default']
export const TextPropertyPanel: typeof import("../components/canvas/TextPropertyPanel.vue")['default']
export const MaterialCard: typeof import("../components/materials/MaterialCard.vue")['default']
export const MaterialCategory: typeof import("../components/materials/MaterialCategory.vue")['default']
export const MaterialPanel: typeof import("../components/materials/MaterialPanel.vue")['default']
export const UserMaterialPanel: typeof import("../components/materials/UserMaterialPanel.vue")['default']
export const FilterPanel: typeof import("../components/filters/FilterPanel.vue")['default']
export const FilterPreview: typeof import("../components/filters/FilterPreview.vue")['default']
export const LabelEditor: typeof import("../components/labels/LabelEditor.vue")['default']
export const LabelPreview: typeof import("../components/labels/LabelPreview.vue")['default']
export const A4Preview: typeof import("../components/export/A4Preview.vue")['default']
export const ExportPanel: typeof import("../components/export/ExportPanel.vue")['default']
export const BackgroundRemovalPanel: typeof import("../components/BackgroundRemovalPanel.vue")['default']
export const ColorAdjustmentPanel: typeof import("../components/color/ColorAdjustmentPanel.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAnimatedButton: typeof import("../components/common/AnimatedButton.vue")['default']
export const LazyWatercolorBg: typeof import("../components/common/WatercolorBg.vue")['default']
export const LazyCanvasToolbar: typeof import("../components/canvas/CanvasToolbar.vue")['default']
export const LazyFabricCanvas: typeof import("../components/canvas/FabricCanvas.vue")['default']
export const LazyLayerPanel: typeof import("../components/canvas/LayerPanel.vue")['default']
export const LazyTextPropertyPanel: typeof import("../components/canvas/TextPropertyPanel.vue")['default']
export const LazyMaterialCard: typeof import("../components/materials/MaterialCard.vue")['default']
export const LazyMaterialCategory: typeof import("../components/materials/MaterialCategory.vue")['default']
export const LazyMaterialPanel: typeof import("../components/materials/MaterialPanel.vue")['default']
export const LazyUserMaterialPanel: typeof import("../components/materials/UserMaterialPanel.vue")['default']
export const LazyFilterPanel: typeof import("../components/filters/FilterPanel.vue")['default']
export const LazyFilterPreview: typeof import("../components/filters/FilterPreview.vue")['default']
export const LazyLabelEditor: typeof import("../components/labels/LabelEditor.vue")['default']
export const LazyLabelPreview: typeof import("../components/labels/LabelPreview.vue")['default']
export const LazyA4Preview: typeof import("../components/export/A4Preview.vue")['default']
export const LazyExportPanel: typeof import("../components/export/ExportPanel.vue")['default']
export const LazyBackgroundRemovalPanel: typeof import("../components/BackgroundRemovalPanel.vue")['default']
export const LazyColorAdjustmentPanel: typeof import("../components/color/ColorAdjustmentPanel.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
